export const GET_MOVIES_START = 'GET_MOVIES_START'
export const GET_MOVIES_COMPLETE = 'GET_MOVIES_COMPLETE'
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR'

export const EXPAND_ALL = 'EXPAND_ALL'
export const COLLAPSE_ALL = 'COLLAPSE_ALL'
